apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    uid: prometheus
    isdefault: true
  - name: Loki
    type: loki
    url: http://loki:3100
    uid: loki
    access: proxy
