name: Backend 

on:
  push:
    branches:
      - main
    paths:
      - backend/**/*.go
      - backend/go.mod
      - .github/workflows/**

  pull_request:
    branches: 
      - main
    paths:
      - backend/**/*.go
      - .github/workflows/**
      - backend/go.mod

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.5' 

      - name: run tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: incompetent-hosting-provider/monorepo

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: backend/
          args: --timeout=5m --new-from-rev=HEAD~3

  build:
    needs:
      - test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.5' 
      
      - name: build
        run: go build -x -v 

  docker-build:
    needs: 
      - test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ./backend
