name: cli

on:
  push:
    branches:
      - main
    paths:
      - cli/**/*.go
      - cli/go.mod
      - .github/workflows/**

  pull_request:
    branches: 
      - main
    paths:
      - cli/**/*.go
      - cli/go.mod
      - .github/workflows/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cli 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4' 

      - name: run tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: incompetent-hosting-provider/monorepo

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: cli/
          args: --timeout=5m --new-from-rev=HEAD~2

  build:
    needs:
      - test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: cli 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4' 
      
      - name: build
        run: go build -x -v 

      - uses: actions/upload-artifact@v4
        with:
          name: cli-build-${{ matrix.os }}
          path: cli/cli
